/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package www.mine;
import java.util.*;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        input1 = new javax.swing.JFormattedTextField();
        input2 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        output1 = new javax.swing.JTextArea();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        m1.setText("Enter Your Weight (kg)");
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        m2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        m2.setText("Enter Your Height (m)");
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 140, -1));

        input1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 6, 146, -1));

        input2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 40, 146, -1));

        output1.setEditable(false);
        output1.setBackground(new java.awt.Color(102, 255, 102));
        output1.setColumns(20);
        output1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        output1.setLineWrap(true);
        output1.setRows(5);
        output1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(output1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 127, 388, -1));

        b1.setBackground(new java.awt.Color(153, 255, 204));
        b1.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        b1.setText("Calculate BMI");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 216, -1));

        b2.setBackground(new java.awt.Color(102, 255, 204));
        b2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        b2.setText("Save As...");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, 30));

        b3.setBackground(new java.awt.Color(102, 255, 204));
        b3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        b3.setText("Close");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 94, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/premium_photo-1701534008693-0eee0632d47a.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String s1, s2, msg = "";
        double w, h, bmi;
        
        s1 = input1.getText();
        w = Double.parseDouble(s1);
        s2 = input2.getText();
        h = Double.parseDouble(s2);
        
        bmi = w / (h * h);
        if(bmi < 18){
            msg = "You are underweight";
        }
        else if (bmi > 25){
            msg = "You are overweight";
        }
        else {
            msg = "You are healthy.";
        }
        String newbmi = String.format("%.2f", bmi);
        String newmsg = "Your BMI is : " + newbmi + "\n"+ msg;
        
        output1.setText(newmsg);
    }//GEN-LAST:event_b1ActionPerformed

    
    void savedata(){
        JFileChooser x = new JFileChooser();
        int a = x.showSaveDialog(this);
        
        if(a == 0){
            try{
                PrintWriter pw = new PrintWriter((new FileWriter(x.getSelectedFile().getPath())), true);
                String msg = output1.getText();
                pw.println(msg);
                pw.close();
            }
            catch(IOException e){
                JOptionPane.showInternalMessageDialog(null, "File Error. Details: "+e);
            }
        }
    }
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        savedata();
    }//GEN-LAST:event_b2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        input1.setText("");
        input2.setText("");
        output1.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JFormattedTextField input1;
    private javax.swing.JFormattedTextField input2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JTextArea output1;
    // End of variables declaration//GEN-END:variables
}
